# For more details, see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform
# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

#languages:
#  JavaScript: true

engines:
  eslint:
    enabled: true

#ratings:
#  paths:
#  - drivers/**.js
#  - "**.js"

#exclude_paths:
#- test/**/*
