language: node_js
sudo: false

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

cache:
  directories:
    - node_modules

# services:
#   - elasticsearch

os:
  - linux
#  - osx

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"